### ISSUE TITLE
ngx-utils does not work in angular-cli 9.1.0

### ISSUE THREAD

**Issue by devangptechuz** [ngx-utils/cookies#22]
ERROR in node_modules/@ngx-utils/cookies/src/cookies-options.service.d.ts:11:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

11     static ɵfac: i0.ɵɵFactoryDef<CookiesOptionsService>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@ngx-utils/cookies/src/cookies.service.d.ts:22:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

22     static ɵfac: i0.ɵɵFactoryDef<CookiesService>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@ngx-utils/cookies/src/browser/browser-cookies.service.d.ts:14:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

14     static ɵfac: i0.ɵɵFactoryDef<BrowserCookiesService>;

**Comment by hojas** [comment]
+1

**Comment by Cafnio** [comment]
Also not working with angular-cli 11.x

**Comment by ctalluri** [comment]
Not working for Angular 13.x also. Any update for this?
